---
  - name: Install postgresql, postgresql-contrib, libpq-dev, python-psycopg2
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
    tags: postgresql

  - name: Change ubuntu postgres password
    become: yes
    user:
      name: postgres
      password: "{{postgresql_pass}}"
    tags: postgresql

  - name: Create database
    become_user: postgres
    postgresql_db:
      name: "{{postgresql_db_name}}"
      login_user: "{{postgresql_user}}"
      login_password: "{{postgresql_pass}}"
      encoding: UTF-8
      template: template0
    tags: postgresql

  - name: Change db user password
    become: yes
    become_user: postgres
    postgresql_user:
      db: "{{postgresql_db_name}}"
      user: "{{postgresql_user}}"
      password: "{{postgresql_pass}}"
    tags: postgresql