---
  - name: Install supervisor
    become: yes
    apt: name=supervisor
    tags: supervisor

  - name: Copy odgassist config to supervisor config folder
    template:
      src: odgassist.j2
      dest: /etc/supervisor/conf.d/odgassist.conf
      mode: 0644
    tags: supervisor

#  - name: Ensure Supervisor is started (if configured).
#    become: yes
#    service:
#      name: supervisord
#      state: started
#      enabled: yes
##    when: supervisor_started
#    tags: supervisor

  - name: Start odgassist with supervisor
    supervisorctl:
      name: odgassist
      state: restarted
      config: /etc/supervisor/supervisord.conf
    tags: supervisor

#  - name: Ensure Supervisor is enabled at boot (if configured).
#    service:
#      name: supervisord
#      enabled: yes
#    when: supervisor_enabled
#    tags: supervisor

