---
  - name: Install Nginx
    apt:
      name: nginx
      state: latest
    tags: nginx

  - name: Copy odgassist config to /sites-available and replace default file
    template:
      src: odgassist_conf.j2
      dest: /etc/nginx/sites-available/default
      mode: 0644
    tags: nginx

  - name: NGINX reload
    service:
      name=nginx
      state=reloaded
    tags: nginx
