---
- name: Apply common configuration to all hosts
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: 'Update packages'
      apt: update_cache=yes
    - name: Create project folder
      file:
        path: "{{ remote_project_folder }}"
        mode: 0755
        owner: "{{ remote_user }}"
        state: directory
    - name: 'Install python2'
      raw: sudo apt-get -y install python
      tags:
        - always
  roles:
    - packages
    - nano
    - git
    - java
    - postgresql
    - tomcat
    - vsftpd
    - locales
    - odgassist
    - supervisor

- name: Apply configuration to hosts with RabbitMQ
  hosts: with_rabbitmq
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - rabbitmq
    - mobile_connector
...