---
- name: apply common configuration to all nodes
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: 'Install python2'
      raw: sudo apt-get -y install python
      tags:
        - always
  roles:
    - packages
    - nano
    - git
    - java
    - postgresql
    - tomcat
    - vsftpd
    - locales
#  pre_tasks:
#    - name: update packages
#      apt: update_cache=yes cache_valid_time=300

- hosts: with_rabbitmq
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - rabbitmq
    - mobile_connector
...