---
#  - name: Install python
#    raw: apt-get -y install python
#
  - name: Install essential packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - python-software-properties
      - software-properties-common
      - python-pip
      - fail2ban
    tags: packages

  - name: Install python-requests packages
    pip: name={{ item }}
    with_items:
      - requests
      - psycopg2
    tags: packages
