---
  - name: Install supervisor
    become: yes
    apt: name=supervisor
    tags: supervisor

  - name: Copy odgassist config to supervisor config folder
    template:
      src: odgassist.j2
      dest: /etc/supervisor/conf.d/odgassist.conf
      mode: 0644
    tags: supervisor

  - name: Start odgassist with supervisor
    supervisorctl:
      name: odgassist
      state: restarted
      config: /etc/supervisor/supervisord.conf
    tags: supervisor
