---
  - name: Install supervisor
    become: yes
    apt: name=supervisor
    tags: supervisor

  - name: Copy odgassist and superlance configs to supervisor config folder
    template:
      src: "{{ item }}"
      dest: /etc/supervisor/conf.d/
      mode: 0644
    with_items:
      - odgassist.conf
      - fatalmailbatch.conf
    tags: supervisor

  - name: Start odgassist, fatalmailbatch with supervisor
    supervisorctl:
      name: "{{ item }}"
      state: restarted
      config: /etc/supervisor/supervisord.conf
    with_items:
      - odgassist
      - fatalmailbatch
    tags: supervisor
