---
- hosts: all
#  pre_tasks:
#    - name: update packages
#      apt: update_cache=yes cache_valid_time=300

#- hosts: local
  sudo: yes
  roles:
    - packages
    - nano
    - git
    - java
    - postgresql
    - rabbitmq
    - tomcat
    - vsftpd
    - locales
    - mobile_connector
...