---
  - name: Install postgresql, postgresql-contrib, libpq-dev, python-psycopg2
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
    tags: postgresql

  - name: Create odg_assist database
    sudo_user: postgres
    postgresql_db:
      name: {{postgresql_db}}
      login_user: {{postgresql_db_user}}
      login_password: {{postgresql_db_pass}}
      encoding: UTF-8
      template: template0
    tags: postgresql

# Не работает блеать!
  - name: Change postgres user password
    sudo: yes
    sudo_user: postgres
    postgresql_user:
      db: odg_assist
      user: postgres
      password: 0000
      force: yes
    tags: postgresql